# /*
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  *
#  *     http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
#  */
runtime: python27
api_version: 1
threadsafe: true

handlers:

# service worker
- url: /service-worker.js
  static_files: dist/service-worker.js
  expiration: 0m
  upload: dist/service-worker.js

# obj files
- url: /(.+\.(obj))
  static_files: dist/\1
  upload: dist/(.+\.(obj))
  application_readable: true
  mime_type: text/plain

# Fonts, images, media
- url: /(.+\.(woff|gif|ico|jpe?g|png|svgz?|ogg|mp3))
  static_files: dist/\1
  upload: dist/(.+\.(woff|gif|ico|jpe?g|png|svgz?|ogg|mp3))
  application_readable: true

# CSS, Javascript, text and other file types
- url: /(.+\.(css|js|xml|txt|json|md|map))
  static_files: dist/\1
  upload: dist/(.+\.(css|js|xml|txt|json|md|map))
  application_readable: true

# if a shared link 
- url: /([0-9]+)/([A-Za-z0-9-_]{6})\/?
  static_files: dist/performance.html
  upload: dist/performance.html
  secure: always

# all other requests, get index.html
- url: /(.*)
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

skip_files:
- ^(.*/)?\..*$
- package.json
- ^node_modules/(.*/)?
- \.gitignore
- ^\.git/.*
- (.*).DS_Store
- ^src/(.*/)?
- ^README\..*
- ^webpack.config\.js